// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestAssignment.Data.Database;

#nullable disable

namespace TestAssignment.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestAssignment.Common.Models.Roll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_added")
                        .HasDefaultValueSql("TIMEZONE('utc', now())");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_deleted");

                    b.Property<double>("Length")
                        .HasColumnType("double precision")
                        .HasColumnName("length");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_rolls");

                    b.ToTable("rolls", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("689f7f26-8cfc-4d58-81ed-6200a43b0813"),
                            DateAdded = new DateTime(2025, 12, 31, 21, 0, 0, 0, DateTimeKind.Utc),
                            Length = 1.0,
                            Weight = 1.0
                        },
                        new
                        {
                            Id = new Guid("b248061c-1001-482d-8270-af253ee3354d"),
                            DateAdded = new DateTime(2026, 1, 1, 21, 0, 0, 0, DateTimeKind.Utc),
                            Length = 100.0,
                            Weight = 50.0
                        },
                        new
                        {
                            Id = new Guid("40bed416-0384-403c-b16d-c5c77e3aa12c"),
                            DateAdded = new DateTime(2026, 1, 2, 21, 0, 0, 0, DateTimeKind.Utc),
                            Length = 200.0,
                            Weight = 200.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
